name: BiomesCompass
version: 1.0.0
description: Adds a special compass which can show you the way to your desired biomes.
author: rusthero

api-version: 1.13
main: io.github.rusthero.biomescompass.BiomesCompass

permissions:
  biomescompass.*:
    children:
      biomescompass.craft: true
      biomescompass.use: true
  biomescompass.craft:
    description: Allows crafting a new biomes compass.
    default: true
  biomescompass.use:
    description: Allows switching biomes of a biomes compass by right clicking.
    default: true